name: Feature Request
description: Suggest an idea for TideRunner
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when...
    validations:
      required: false

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would improve experience
        - High - Essential for my use case
    validations:
      required: true

  - type: checkboxes
    id: areas
    attributes:
      label: Which area does this feature affect?
      options:
        - label: Species database
        - label: Marine conditions
        - label: Fishing times graph
        - label: Map functionality
        - label: UI/UX
        - label: Data sources/APIs
        - label: Other
